### PR TITLE
 added possibility to use nprinting server on different host 

### PR DESCRIPTION
**Pull request by and29**
Fix of the following issues:
- conflict when clicking on Nprinting Report history when multiple buttons are present in the page
- CORS request blocking by firefox when nprinting server is on a different host
- font woff2 error

### CODE REVIEW

**Comment by bohua** [comment]
merge

**Comment by GINQO** [comment]
Hi Andrea,

Just wondering why you might have closed this update, it seems like just the thing I need for one of our setups.  Did you run into any issues that prevented this technique from being effective?


Thanks,
GINQO

**Comment by and29** [comment]
Hi GINQO,

this version is closed because it works in an environment but it doesn't in another. I still didn't figure it out why, that's why I was waiting to reopen it. But I think you can use it.

Thank you,
Andrea

**Comment by GINQO** [comment]
Thank you, sir, & thanks for your effort on the project...


Cheers,
GINQO

**Comment by GINQO** [comment]
Actually, I did come across something in my travels while reading up on CORS that might be useful:  it sounds like it is the responding server (e.g. NPrinting) that needs to apply the _Access-Control-Allow-Origin_ header, the request needs to provide the _Origin_ header (which is matched by the browser against the _Access-Control-Allow-Origin_), so I'm not sure if this code change would have the desired effect (as it is applying the _Access-Control-Allow-Origin_ to the request & not the response).

**Comment by and29** [comment]
You are right! I did it because I was having CORS error and I learned later what you just explained. I'll remove them and push the changes on my fork. 
Thank you!
Andrea

**Comment by bohua** [comment]
Hi Andrea,

Sorry for a late reply. Just back from vacation.

I think it’s a mistake action when I cleaning the repo. I will recover it. :)

Thanks a lot for your contribution!
//Bohua

**Comment by and29** [comment]
Hi bohua,
thank you for the extension!

**Comment by GINQO** [comment]
Yes, indeed, thank you, Bohua!

**Pull request merged**
